# Generated by Django 5.1.1 on 2024-12-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
