# Generated by Django 5.1.1 on 2024-12-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_pedido_estado_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='YapePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.ImageField(upload_to='yape_qr/')),
                ('numero_telefono', models.CharField(max_length=9)),
                ('nombre_beneficiario', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pago',
        ),
    ]
