# Generated by Django 5.1.1 on 2024-12-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_yapepago_remove_pedido_estado_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YapePago',
        ),
    ]
