# Generated by Django 5.1.1 on 2024-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_delete_yapepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
